---
title: 'R-Lab: Random Forests Residual Analysis'
output:
  html_document: default
  word_document: default
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path='Figs/', tidy = TRUE, warning=FALSE, message=FALSE)
```

http://www.milbo.org/doc/plotres-notes.pdf


```{r}
library(randomForest)
library(plotmo)
library(RCurl)
set.seed(1)

data <- read.csv(text=getURL("https://raw.githubusercontent.com/shuailab/ind_498/master/resource/data/AD_hd.csv"))

target <-  data$AGE
rm_indx <-  which( colnames(data) %in% c("AGE","ID","TOTAL13","MMSCORE") ) 
X <- data[,-rm_indx]
rf.mod <- randomForest(X,target, ntrees =  10)

plotres(rf.mod, which = 3)

plotres(rf.mod, which = 4)

```

```{r}
require(ggplot2)
set.seed(1)
X <- data.frame( X1 = runif(30, min = -1, max = 1) )
target <- 0.5 * X$X1 # + 0.5 * X$X2
rf <- randomForest( X, target)

plotres(rf, which = 3)
plotres(rf, which = 4)

testing <- data.frame( X1 = runif(1000, min = -2, max = 2) )
target <- 0.5 * testing$X1 # + 0.5 * X$X2
pred <- predict(rf,testing,type="response")
pred.data <- cbind(testing,target,pred)
ggplot(pred.data,aes(x=X1,y=pred))+geom_point(size=0.5)


```



